name: 004 - Manual Co-author PR 2️⃣

on:
  workflow_dispatch:

jobs:
  coauthor_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Create multiple co-authored commits
        run: |
          mkdir -p temp
          rm -rf temp/*
          for i in {1..3}; do
            FILE="temp/commit_$i.txt"
            echo "Manual staged update $i at $(date -u)" >> $FILE
            git add $FILE
            git commit -m "chore: update $i" -m "Co-authored-by: ElianeOliota <ElianeOliota@users.noreply.github.com>"
          done

      - name: Push branch and open PR
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          BRANCH="manual/achieve-coauthor-$(date +%s)"
          git checkout -b $BRANCH
          git push origin $BRANCH
          gh auth setup-git
          gh pr create --title "Manual Merge PR with Co-authors" --body "Created by automation, merged manually." --head $BRANCH
