name: Auto Commit

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          mkdir -p commits
          bash generate_file.sh
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add commits/
          git commit -m "Auto commit at $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
