name: Auto Commit

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          mkdir -p commits
          bash generate_file.sh
          git config user.name "Rubem Oliota"
          git config user.email "oliota@users.noreply.github.com"
          git add commits/
          git commit -m "Auto commit at $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
