name: Daily Contributions

on:
  schedule:
    - cron: '*/5 * * * *'  # check every 5 minutes
  workflow_dispatch:

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install axios
      - name: Run contribution script 
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          EXEC_HOUR: '12'
          EXEC_MIN: '30'
        run: node scripts/daily_contribution.js
