name: Hourly Contribution

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "$(date -u '+%Y-%m-%d %H:%M:%S')" >> contribuition.txt
      - run: |
          git config user.name "oliota"
          git config user.email "oliota@users.noreply.github.com"
          git add contribuition.txt
          git commit -m "Add hourly contribution"
          git push
